## lifecycle of ds

In [ ]:
                                        Data read
                                            |
                                        Data cleaning
                                            |
                                        Data Analysis
                                            |
                                     Feature Engineering
                                            |
                                    Feature Selection
                                            |
                                        Model Development
                                            |
                                        Model Evaulation
                                            |
                                        Model tuning
                                            |
                                        Model deployment

## Feature Engineering

## simple: our data will be modified

- So far we have performed feature analysis

    - data frame **quick checks**

    - **categorical column analysis** 

    - **Bar charts, pie charts, frequency tables**

    - **Numerical** column analysis 

    - histograms, boxplot , outliers,

    - **BiVaraite Multi-varaite analysis**

    - **correlation**

- Now we need to learn feature engineering

    - we will create a new column for better ML models

    - we will perform the **Encoding** , which is convert to  categorical to numerical data

    - we will do **data transformation**

    - we will perform the **Scaling : Standardization and Normalaization**
 
    - we will perfrom the **missing value analysis**

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
visa_df = pd.read_csv(r"C:\Users\Kasipetaraviteja\Documents\Data_files\Visadataset.csv")

In [3]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [4]:
cat = visa_df.select_dtypes(include='object').columns
num = visa_df.select_dtypes(exclude='object').columns

In [9]:
cat,num

(Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
        'requires_job_training', 'region_of_employment', 'unit_of_wage',
        'full_time_position', 'case_status'],
       dtype='object'),
 Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object'))

## case_status

In [5]:
visa_df['case_status']

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

### step-1 first check how many unique lables are there

In [6]:
# step-1 first check how many unique lables are there
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

### step -2 create a dictionary  (find something)  fit

In [7]:
# create a dictionary

d = {'Certified': 0 , 'Denied':1}
d

{'Certified': 0, 'Denied': 1}

### step-3 map the above dictionary with original column   (transform)

In [8]:
# map the above dictionary with original column

visa_df['case_status'] = visa_df['case_status'].map(d)

In [9]:
visa_df['case_status']   # now the values are replaced with those certified and denied

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

## education_of_employee

In [15]:
visa_df['education_of_employee']

0        High School
1           Master's
2         Bachelor's
3         Bachelor's
4           Master's
            ...
25475     Bachelor's
25476    High School
25477       Master's
25478       Master's
25479     Bachelor's
Name: education_of_employee, Length: 25480, dtype: object

In [16]:
visa_df['education_of_employee'].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [1]:
# hard coding
d1 = {'High School' : 0, "Master's":1, "Bachelor's":2, "Doctorate":3}

In [18]:
d1

{'High School': 0, "Master's": 1, "Bachelor's": 2, 'Doctorate': 3}

In [19]:
visa_df['education_of_employee'] = visa_df['education_of_employee'].map(d1)

In [22]:
visa_df['education_of_employee']

0        0
1        1
2        2
3        2
4        1
        ..
25475    2
25476    0
25477    1
25478    1
25479    2
Name: education_of_employee, Length: 25480, dtype: int64

In [36]:
lables = sorted(visa_df['education_of_employee'].unique())     # list having unique items
d1 = {j : i for i , j in enumerate(lables) }
d1

{"Bachelor's": 0, 'Doctorate': 1, 'High School': 2, "Master's": 3}

In [38]:
visa_df['education_of_employee'] = visa_df['education_of_employee'].map(d1)

In [39]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,2,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,3,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,0,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,0,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,3,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,0,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,2,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,3,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,3,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,0,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

# types  of Encoders:

### LableEncoder

### OrdinalEncoder

In [ ]:
Ramesh Suresh  Sathi
s  == > Nominal data

In [ ]:
Education             LableEncoder                OrdinalEncoder
-----------------------------------------------------------------

HighSchool               2                            0

Bachelor                 0                            1

Masters                  3                            2

Doctarate                1                            3                        


1   0  2    3   ====> ML model sees  this  : 3 > 2 > 1 > 0

which indicates  :  > Masters > HighSchool > Docaterate > Bacheloers

In [10]:
visa_df = pd.read_csv(r"C:\Users\Kasipetaraviteja\Documents\Data_files\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

## sklearn  :   **Package**

    - preprocessing   : **Module**

        - **LableEncoder**    :  **class**

            - **fit_transform**   : **method**

In [12]:
import sklearn 
sklearn.preprocessing

from sklearn import preprocessing
preprocessing.LableEncoder()

from sklearn.preprocessing import LabelEncoder


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform

In [44]:
sklearn.preprocessing

TypeError: 'module' object is not callable

In [60]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit

In [ ]:
from package.module import class
var = class()
var.fit          # only finds something that want to replace/encode/modify the data/column
var.fit_transform       # find something and modify the data/column

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit()

In [15]:
visa_df = pd.read_csv(r"C:\Users\Kasipetaraviteja\Documents\Data_files\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

## labelEncoder()

- fit_transform   ===>  finds something and transform/modify the data

-  coverts the text to digits ===> automates

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0], shape=(25480,))

In [17]:
visa_df['case_status']

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

In [18]:
visa_df['case_status'] = le.fit_transform(visa_df['case_status'])

In [19]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [8]:
visa_df['region_of_employment'] = le.fit_transform(visa_df['region_of_employment'])

In [9]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,4,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,2,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,4,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,4,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,3,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,3,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,2,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,3,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,4,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,1,70876.9100,Year,Y,Certified

## apply to all columns

In [10]:
visa_df = pd.read_csv(r"C:\Users\Kasipetaraviteja\Documents\Data_files\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [11]:
cat = visa_df.select_dtypes(include='object').columns.tolist()
cat

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'region_of_employment',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in cat[1:]:       # dont consider  CASE_ID
    visa_df[i] = le.fit_transform(visa_df[i])

In [13]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

## ordinal columns

In [14]:
visa_df = pd.read_csv(r"C:\Users\Kasipetaraviteja\Documents\Data_files\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [15]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
for i in cat[1:]:       # dont consider  CASE_ID
    visa_df[i] = oe.fit_transform(visa_df[[i]])          # 2 dimensional == > [ [] ]

In [16]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1.0,2.0,0.0,0.0,14513,2007,4.0,592.2029,0.0,1.0,1.0
1,EZYV02,1.0,3.0,1.0,0.0,2412,2002,2.0,83425.6500,3.0,1.0,0.0
2,EZYV03,1.0,0.0,0.0,1.0,44444,2008,4.0,122996.8600,3.0,1.0,1.0
3,EZYV04,1.0,0.0,0.0,0.0,98,1897,4.0,83434.0300,3.0,1.0,1.0
4,EZYV05,0.0,3.0,1.0,0.0,1082,2005,3.0,149907.3900,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1.0,0.0,1.0,1.0,2601,2008,3.0,77092.5700,3.0,1.0,0.0
25476,EZYV25477,1.0,2.0,1.0,0.0,3274,2006,2.0,279174.7900,3.0,1.0,0.0
25477,EZYV25478,1.0,3.0,1.0,0.0,1121,1910,3.0,146298.8500,3.0,0.0,0.0
25478,EZYV25479,1.0,3.0,1.0,1.0,1918,1887,4.0,86154.7700,3.0,1.0,0.0
25479,EZYV25480,1.0,0.0,1.0,0.0,3195,1960,1.0,70876.9100,3.0,1.0,0.0

In [18]:
visa_df = pd.read_csv(r"C:\Users\Kasipetaraviteja\Documents\Data_files\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

## pd.get_dummies

In [ ]:
-  get dummies is a way to represent the categorical columns   to numerical 

-  first it will check what are the labels in a column 

- for ex : case status has  two labels

    - Denied and Certified  ddnb

- So it will create 2 new columns based on lables

    - col1  : case_staus_Denied

    - col2  : case_status_Certified


case_status     |    case_status_Denied   |   case_status_Certified   | ddnb

denied          |          1                            0

certified       |          0                             1

certified       |          0                             1

denied          |          1                              0

.

## It is also called as One Hot Encoder**

- It makes new columns are independent each other

- some of **ML algorithms expect  ==> that `columns should be independent  each other`**

In [19]:
pd.get_dummies(visa_df)

,no_of_employees,yr_of_estab,prevailing_wage,case_id_EZYV01,case_id_EZYV02,case_id_EZYV03,case_id_EZYV04,case_id_EZYV05,case_id_EZYV06,case_id_EZYV07,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,14513,2007,592.2029,True,False,False,False,False,False,False,...,False,True,True,False,False,False,False,True,False,True
1,2412,2002,83425.6500,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
2,44444,2008,122996.8600,False,False,True,False,False,False,False,...,False,True,False,False,False,True,False,True,False,True
3,98,1897,83434.0300,False,False,False,True,False,False,False,...,False,True,False,False,False,True,False,True,False,True
4,1082,2005,149907.3900,False,False,False,False,True,False,False,...,True,False,False,False,False,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,2601,2008,77092.5700,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,True,True,False
25476,3274,2006,279174.7900,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
25477,1121,1910,146298.8500,False,False,False,False,False,False,False,...,True,False,False,False,False,True,True,False,True,False
25478,1918,1887,86154.7700,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,True,True,False
25479,3195,1960,70876.9100,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False

In [21]:
visa_df['case_status'] == 'Denied'

0         True
1        False
2         True
3         True
4        False
         ...
25475    False
25476    False
25477    False
25478    False
25479    False
Name: case_status, Length: 25480, dtype: bool

In [42]:
pd.get_dummies(visa_df['case_status'])  # boolean will come (default)

       Certified  Denied
0          False    True
1           True   False
2          False    True
3          False    True
4           True   False
...          ...     ...
25475       True   False
25476       True   False
25477       True   False
25478       True   False
25479       True   False

[25480 rows x 2 columns]

In [23]:
pd.get_dummies(visa_df['case_status'],dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]

In [44]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified